config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'links#new'
  get '/s/:slug', to: 'links#show', as: :short
  resources :links, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# Model class for link
class Link < ApplicationRecord
  validates_presence_of :url
  validates :url, format: URI.regexp(%w[http https])
  validates_uniqueness_of :slug
  validates_length_of :url, within: 3..255, on: :create, message: 'too long'
  validates_length_of :slug, within: 3..255, on: :create, message: 'too long'
  before_validation :generate_slug

  def short
    Rails.application.routes.url_helpers.short_url(slug: slug)
  end

  private

  def generate_slug
    self.slug = SecureRandom.uuid[0..5] unless slug.present?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
# links controller
class LinksController < ApplicationController
  before_action :set_link, only: %i[new create]
  def index
    @links = Link.all
  end

  def show
    @link = Link.find_by_slug(params[:slug])
    render 'errors/404', status: 404 if @link.nil?
    @link.update_attribute(:clicked, @link.clicked + 1)
    redirect_to @link.url
  end

  def new; end

  def create
    @link.assign_attributes(link_params)
    @link.save!
    flash[:notice] = 'Url shortened successfully'
    redirect_to links_path
  rescue StandardError => e
    Rails.logger.error e.backtrace.join("\n")
    flash[:alert]  = e.message
    render 'new'
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def set_link
    @link = Link.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorteningService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<div class="container-fluid text-center">
  <h1> Showing all shortened URL's</h1>
  <%= link_to('Short More Url', new_link_path) %>
    <table class="table">
      <thead>
      <th>
        Long Url
      </th>
      <th>
        Short Url
      </th>
      <th>
        Clicked Counter
      </th>
      </thead>
      <tbody>
      <% @links.each do |link| %>
        <tr>
          <td>
            <a href=<%= link.url %> class="link-danger"> <%=link.url %></a>
          </td>
          <td>
            <a href=<%= link.short %> class="link-primary"> <%=link.short %></a>
          </td>
          <td>
            <%= link.clicked %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>

app/views/links/new.html.erb
<div class="container-fluid text-center p-5 m-5">
  <h1>Type Long Url to shorten</h1>
  <% flash.each do |type, msg| %>
    <div>
      <p class="text-danger"><%= msg %></p>
    </div>
  <% end %>
  <%= form_for(@link, locale: true) do |f|%>
    <div>
      <div>
        Long URL: <%= f.text_field :url, placeholder: 'paste long url here ' %>
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>